Repository arktwin/arktwin, pull requests merged in 2024-12, with the labels that each got.

#168 Fix commands to generate OpenAPI YAML files
  .github/workflows/github-pages.yaml
Labels: bug

#169 Add tag types for Timestamp and Duration to improve type safety
  arktwin/build.sbt
  arktwin/center/src/main/scala/arktwin/center/actors/Chart.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/ClockConfig.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/common/src/main/protobuf/arktwin/pacakge.proto
  arktwin/common/src/main/scala/arktwin/center/services/ClockBaseEx.scala
  arktwin/common/src/main/scala/arktwin/common/TaggedDurationHistogram.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimeTag.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TransformEnuEx.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/DurationSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedDurationSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedTimestampSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TimestampSuite.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeKamon.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: refactor

#170 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.10
  arktwin/build.sbt
Labels: dependencies

#172 Update jsoniter-scala-macros to 2.32.0
  arktwin/build.sbt
Labels: dependencies

#173 Update scribe, scribe-slf4j2 to 3.15.3
  arktwin/build.sbt
Labels: dependencies

#174 Update scala3-library to 3.6.2
  arktwin/build.sbt
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#177 Update gatling-sbt to 4.11.1
  arktwin/project/plugins.sbt
Labels: dependencies

#175 Update openapi-circe-yaml to 0.11.4
  arktwin/build.sbt
Labels: dependencies

#176 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.11
  arktwin/build.sbt
Labels: dependencies

#179 Validate configs
  arktwin/build.sbt
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/configs/AtlasConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/ClockConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/DynamicCenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/common/src/main/scala/arktwin/common/TaggedDurationHistogram.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedDurationSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedTimestampSuite.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CullingConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/DynamicEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/Vector3Config.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
Labels: enhancement
