Repository arktwin/arktwin, pull requests merged in 2024-08, with the labels that each got.

#50 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.0
  arktwin/build.sbt
Labels: dependencies

#51 Make actor mailboxes configurable
  README.md
  arktwin/build.sbt
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartReceiverParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorderParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartSenderParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/common/src/main/scala/arktwin/common/MailboxConfig.scala
  arktwin/edge/src/main/resources/pekko.conf
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Register.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
Labels: enhancement

#52 Add metrics for dead letters
  README.md
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/edge/src/main/resources/pekko.conf
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeKamon.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
Labels: enhancement

#55 Change center culling messaging architecture
  README.md
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartReceiver.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartReceiverParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorderParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRouter.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartSender.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartSenderParent.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/CommonMessages.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/center/src/main/scala/arktwin/center/util/CommonMessages.scala
  arktwin/common/src/main/protobuf/arktwin/center/services/chart.proto
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Register.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ClockConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/CommonMessages.scala
  docs/center-culling.drawio
  docs/center-culling.png
  docs/diagrams.puml
  docs/diagrams/messaging.png
Labels: enhancement

#56 Update openapi-circe-yaml to 0.11.3
  arktwin/build.sbt
Labels: dependencies

#57 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.1
  arktwin/build.sbt
Labels: dependencies

#58 Update scala to 3.5.0
  .github/workflows/scala-ci.yaml
  arktwin/.scalafix.conf
  arktwin/.scalafmt.conf
  arktwin/build.sbt
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRouter.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/services/AdminService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/common/src/main/scala/arktwin/center/services/ClockBaseEx.scala
  arktwin/common/src/main/scala/arktwin/common/LoggerConfigurator.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/QuaternionEnuEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TransformEnuEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/Vector3EnuEx.scala
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Register.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeKamon.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/JsonDerivation.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/util/JsonDerivationSuite.scala
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#15 Update scalapb-validate-codegen, ... to 0.3.5
  arktwin/project/plugins.sbt
Labels: dependencies

#59 Change ChartRecorder mailbox bounded
  arktwin/center/src/main/resources/pekko.conf
  docs/center-culling.drawio
  docs/center-culling.png
  docs/diagrams.puml
  docs/diagrams/messaging.png
Labels: enhancement

#60 Refactor
  arktwin/build.sbt
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/scala/arktwin/center/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Chart.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/services/AdminService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/test/resources/application-test.conf
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/center/src/test/scala/arktwin/center/test/ActorTestBase.scala
  arktwin/common/src/main/protobuf/arktwin/center/services/admin.proto
  arktwin/common/src/main/protobuf/arktwin/center/services/register.proto
  arktwin/common/src/main/scala/arktwin/common/MailboxConfig.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampEx.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/DurationSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TimestampSuite.scala
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Register.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/RegisterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/util/JsonDerivationSuite.scala
  docs/center-culling.drawio
  docs/center-culling.png
  docs/diagrams.puml
  docs/diagrams/messaging.png
Labels: refactor

#61 Change time management of grid culling
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/util/CommonMessages.scala
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
Labels: enhancement

#62 Update jsoniter-scala-macros to 2.30.8
  arktwin/build.sbt
Labels: dependencies

#63 Update base docker images
  arktwin/project/build.properties
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: ci

#64 Update jsoniter-scala-macros to 2.30.9
  arktwin/build.sbt
Labels: dependencies

#65 use build pipelining
  arktwin/build.sbt
Labels: ci
