Repository arktwin/arktwin, pull requests merged in 2024-09, with the labels that each got.

#66 Refactor configurations
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/configs/AtlasConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/ClockConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/DynamicCenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CullingConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/DynamicEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/Vector3Config.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Vector3.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: refactor

#67 Use extension methods
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/common/src/main/scala/arktwin/center/services/ClockBaseEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/QuaternionEnuEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/TransformEnuEx.scala
  arktwin/common/src/main/scala/arktwin/common/data/Vector3EnuEx.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
Labels: refactor

#72 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.3
  arktwin/build.sbt
Labels: dependencies

#78 Update jsoniter-scala-macros to 2.30.11
  arktwin/build.sbt
Labels: dependencies

#79 Update scala3-library to 3.5.1
  arktwin/build.sbt
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#75 Add viewer to ArkTwin Edge
  .gitignore
  README.md
  arktwin/build.sbt
  arktwin/edge/src/main/resources/docs.html
  arktwin/edge/src/main/resources/root.html
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/viewer/.npmrc
  arktwin/viewer/.prettierignore
  arktwin/viewer/.prettierrc
  arktwin/viewer/eslint.config.js
  arktwin/viewer/index.html
  arktwin/viewer/package-lock.json
  arktwin/viewer/package.json
  arktwin/viewer/src/functions.tsx
  arktwin/viewer/src/index.tsx
  arktwin/viewer/src/types.ts
  arktwin/viewer/tsconfig.json
  arktwin/viewer/vite.config.ts
  docker/center.dockerfile
  docker/center.dockerfile.dockerignore
  docker/edge.dockerfile
  docker/edge.dockerfile.dockerignore
  docs/diagrams.puml
  docs/diagrams/messaging.png
Labels: enhancement

#80 Migrate from ESLint and Prettier to Biome
  README.md
  arktwin/viewer/.prettierrc
  arktwin/viewer/biome.json
  arktwin/viewer/eslint.config.js
  arktwin/viewer/package-lock.json
  arktwin/viewer/package.json
  arktwin/viewer/src/functions.tsx
  arktwin/viewer/src/index.tsx
Labels: refactor

#81 Refactor
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/viewer/.prettierignore
Labels: refactor

#84 Update jsoniter-scala-macros to 2.30.12
  arktwin/build.sbt
Labels: dependencies

#85 Update sbt-scalafix to 0.13.0
  arktwin/project/plugins.sbt
Labels: dependencies

#86 Update jsoniter-scala-macros to 2.30.13
  arktwin/build.sbt
Labels: dependencies
