Repository arktwin/arktwin, pull requests merged in 2024-11, with the labels that each got.

#135 Round numbers in the agents viewer
  arktwin/viewer/src/functions.tsx
Labels: enhancement

#136 Add port auto increment feature
  .github/workflows/scala-ci.yaml
  README.md
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  docker/edge.sh
Labels: enhancement

#137 Update sbt-buildinfo to 0.13.0
  arktwin/project/plugins.sbt
Labels: dependencies

#140 Update gatling-sbt to 4.10.2
  arktwin/project/plugins.sbt
Labels: dependencies

#138 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.8
  arktwin/build.sbt
Labels: dependencies

#139 Update scalapb-validate-codegen, ... to 0.3.6
  arktwin/project/plugins.sbt
Labels: dependencies

#146 Update gatling-charts-highcharts to 3.13.1
  arktwin/build.sbt
Labels: dependencies

#147 Update pekko-grpc-runtime_3, ... to 1.1.1
  arktwin/project/plugins.sbt
Labels: dependencies

#144 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.9
  arktwin/build.sbt
Labels: dependencies

#143 Update jsoniter-scala-macros to 2.31.3
  arktwin/build.sbt
Labels: dependencies

#148 Update pureconfig-core to 0.17.8
  arktwin/build.sbt
Labels: dependencies

#149 Remove deprecated import
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
Labels: refactor

#150 Add an extra field to transform data structure
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/common/src/main/protobuf/arktwin/common/data/transform_enu.proto
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: enhancement

#151 Generate license lists for libraries that ArkTwin Center or Edge depends on
  .github/workflows/scala-ci.yaml
  README.md
  arktwin/build.sbt
  arktwin/project/plugins.sbt
Labels: enhancement

#152 Generate license lists for libraries that ArkTwin Edge Neighbors Viewer depends on
  .github/workflows/cla-assistant.yaml
  .github/workflows/dependency-submission.yaml
  .github/workflows/typescript-ci.yaml
  README.md
  arktwin/viewer/package-lock.json
  arktwin/viewer/package.json
Labels: enhancement

#153 Add environment variable ARKTWIN_CENTER_TLS
  README.md
  arktwin/edge/src/main/resources/pekko.conf
Labels: enhancement

#154 Rename environment variable ARKTWIN_CENTER_PROMETHEUS_PUSHGATEWAY_ENABLED to ARKTWIN_CENTER_PROMETHEUS_PUSHGATEWAY
  README.md
  arktwin/center/src/main/resources/kamon.conf
  arktwin/edge/src/main/resources/kamon.conf
Labels: enhancement

#155 Remove deprecated commands of ArkTwin Edge
  .github/workflows/scala-ci.yaml
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
Labels: refactor

#156 Fix build command to avoid a bug where viewer assets are sometimes not included in the JAR
  README.md
  arktwin/build.sbt
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: bug
