Repository arktwin/arktwin, pull requests merged in 2024-07, with the labels that each got.

#29 Configure automatically generated release notes
  .github/release.yml
  .github/scala-steward.conf
Labels: ci

#30 Update jsoniter-scala-macros to 2.30.4
  arktwin/build.sbt
Labels: dependencies

#31 Update sbt, sbt-dependency-tree to 1.10.1
  arktwin/project/build.properties
Labels: dependencies

#32 Update a messaging architecture diagram
  README.md
  docs/diagrams.puml
  docs/diagrams/messaging.png
Labels: documentation

#33 Add JAR build stage in Dockerfile
  .github/workflows/scala-ci.yml
  README.md
  arktwin/build.sbt
  arktwin/docker/center.dockerfile
  arktwin/docker/center.dockerfile.dockerignore
  arktwin/docker/edge.dockerfile
  arktwin/docker/edge.dockerfile.dockerignore
  arktwin/project/build.properties
Labels: ci

#34 Move docker directory
  .github/workflows/scala-ci.yml
  README.md
  docker/center.dockerfile
  docker/center.dockerfile.dockerignore
  docker/edge.dockerfile
  docker/edge.dockerfile.dockerignore
  docker/edge.sh
Labels: ci

#36 Update tapir-core, tapir-jsoniter-scala, ... to 1.10.13
  arktwin/build.sbt
Labels: dependencies

#35 Update jsoniter-scala-macros to 2.30.6
  arktwin/build.sbt
Labels: dependencies

#38 Deploy Swagger UI on GitHub Pages
  .github/workflows/github-pages.yaml
  README.md
  pages/dist/swagger-ui/center/index.html
  pages/dist/swagger-ui/edge/index.html
Labels: ci

#39 Refactor YAML files
  .coderabbit.yaml
  .github/release.yaml
  .github/scala-steward.conf
  .github/workflows/cla-assistant.yaml
  .github/workflows/dependency-submission.yaml
  .github/workflows/scala-ci.yaml
  .github/workflows/scala-ci.yml
  README.md
Labels: ci

#40 Turn off CodeRabbit
  .coderabbit.yaml
Labels: ci

#41 Deploy Swagger UI on release tags
  .github/workflows/github-pages.yaml
Labels: ci

#43 Update openapi-circe-yaml to 0.11.0
  arktwin/build.sbt
Labels: dependencies

#45 Format dockerfiles
  arktwin/build.sbt
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: ci

#46 Change the logger library to scribe
  README.md
  arktwin/build.sbt
  arktwin/center/src/main/resources/logback.xml
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/center/src/test/logback-test.xml
  arktwin/common/src/main/scala/arktwin/common/LoggerConfigurator.scala
  arktwin/edge/src/main/resources/logback.xml
  arktwin/edge/src/main/resources/pekko.conf
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
  arktwin/edge/src/test/resources/logback-test.xml
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/RegisterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/test/ActorTestBase.scala
Labels: enhancement

#49 Update scalafmt-core to 3.8.3
  arktwin/.scalafmt.conf
Labels: dependencies

#48 Update tapir-core, tapir-jsoniter-scala, ... to 1.10.15
  arktwin/build.sbt
Labels: dependencies

#47 Update openapi-circe-yaml to 0.11.2
  arktwin/build.sbt
Labels: dependencies
