Repository arktwin/arktwin, pull requests merged in 2025-01, with the labels that each got.

#189 Update openapi-circe-yaml to 0.11.5
  arktwin/build.sbt
Labels: dependencies

#191 Rename ARKTWIN_CENTER_TLS to ARKTWIN_EDGE_GRPC_CLIENT_TLS
  README.md
  arktwin/edge/src/main/resources/pekko.conf
Labels: enhancement

#193 Update jsoniter-scala-macros to 2.33.0
  arktwin/build.sbt
Labels: dependencies

#194 Update pekko-actor-testkit-typed, ... to 1.1.3
  arktwin/build.sbt
Labels: dependencies

#196 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.12
  arktwin/build.sbt
Labels: dependencies

#195 Update scribe, scribe-slf4j2 to 3.16.0
  arktwin/build.sbt
Labels: dependencies

#199 Rename arktwin_edge_rest_simulation_latency to arktwin_edge_rest_virtual_latency
  README.md
Labels: enhancement

#205 Update scalafmt-core to 3.8.5
  arktwin/.scalafmt.conf
Labels: dependencies

#202 Update sbt-assembly to 2.3.1
  arktwin/project/plugins.sbt
Labels: dependencies

#204 Update sbt-scalafmt to 2.5.4
  arktwin/project/plugins.sbt
Labels: dependencies

#203 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.13
  arktwin/build.sbt
Labels: dependencies

#206 Fix the changelogs step in scala-ci
  .github/workflows/scala-ci.yaml
  arktwin/common/src/main/scala/arktwin/common/LoggerConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
Labels: ci

#201 Update sbt-scalafix to 0.14.0
  arktwin/project/plugins.sbt
Labels: dependencies

#207 Change configuration files to camelCase aligning with the REST API
  arktwin/build.sbt
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
Labels: enhancement

#192 Improve Coordinate Transformation Feature
  arktwin/center/src/main/scala/arktwin/center/configs/AtlasConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/ClockConfig.scala
  arktwin/common/src/main/scala/arktwin/common/EnumConfigIdentityReader.scala
  arktwin/common/src/main/scala/arktwin/common/LoggerConfigurator.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/common/src/main/scala/arktwin/common/data/Vector3EnuEx.scala
  arktwin/e2e/src/test/scala/arktwin/e2e/endpoints/EdgeConfigCoordinatePutScenario.scala
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/AxisConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/Vector3Config.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Vector3.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/JsonDerivation.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: enhancement

#208 Unify type variables to A
  arktwin/common/src/main/scala/arktwin/common/TaggedDurationHistogram.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/ErrorStatus.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/JsonDerivation.scala
Labels: chore

#209 Add lineEndings configuration
  arktwin/.scalafmt.conf
Labels: chore
