Repository arktwin/arktwin, pull requests merged in 2025-07, with the labels that each got.

#344 Add performance guidance to EdgeAgentsPut endpoint and reorder description field
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeBulk.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
Labels: documentation

#346 Refactor Kamon metric formatting and improve code organization
  arktwin/build.sbt
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/center/src/test/scala/arktwin/center/configs/CenterConfigSpec.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/util/GrpcHeaderKeys.scala
  arktwin/common/src/main/scala/arktwin/common/util/KamonFormatter.scala
  arktwin/common/src/main/scala/arktwin/common/util/KamonTagKeys.scala
  arktwin/common/src/main/scala/arktwin/common/util/TimeConstants.scala
  arktwin/common/src/main/scala/arktwin/common/util/TimeTag.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedDurationSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedTimestampSpec.scala
  arktwin/common/src/test/scala/arktwin/common/util/KamonFormatterSpec.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ClockConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeKamon.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/ErrorStatus.scala
  arktwin/edge/src/test/scala/arktwin/edge/configs/EdgeConfigSpec.scala
Labels: ci

#352 Update jsoniter-scala-core, ... to 2.36.7
  arktwin/build.sbt
Labels: dependencies

#350 Update sbt-scalafmt to 2.5.5
  arktwin/project/plugins.sbt
Labels: dependencies

#349 Update gatling-sbt to 4.16.1
  arktwin/project/plugins.sbt
Labels: dependencies

#348 Update openapi-circe-yaml to 0.11.10
  arktwin/build.sbt
Labels: dependencies

#351 Update scalafmt-core to 3.9.8
  arktwin/.scalafmt.conf
Labels: dependencies

#355 Update gatling-sbt to 4.16.2
  arktwin/project/plugins.sbt
Labels: dependencies

#354 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.36
  arktwin/build.sbt
Labels: dependencies

#357 Update sbt to 1.11.3 in dockerfiles
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#361 Update pekko-actor-testkit-typed, ... to 1.1.5
  arktwin/build.sbt
Labels: dependencies

#362 Update jsoniter-scala-core, ... to 2.37.0
  arktwin/build.sbt
Labels: dependencies

#363 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.40
  arktwin/build.sbt
Labels: dependencies
