Repository arktwin/arktwin, pull requests merged in 2025-08, with the labels that each got.

#377 Bump node from 22.x to 24.x in /arktwin/viewer
  README.md
  arktwin/viewer/package-lock.json
  arktwin/viewer/package.json
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#378 Add error handling for npm commands in viewer build
  arktwin/build.sbt
Labels: ci

#381 Refactor Clock, Chart, and EdgeConfiguratorClock
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ClockConnector.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSpec.scala
Labels: chore

#383 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.41
  arktwin/build.sbt
Labels: dependencies

#388 Decouple unit tests from OpenAPI examples
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSpec.scala
Labels: chore

#391 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.42
  arktwin/build.sbt
Labels: dependencies

#393 Reorder configuration fields alphabetically for consistency
  arktwin/center/src/main/resources/kamon.conf
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/configs/ClockConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/center/src/test/scala/arktwin/center/configs/CenterConfigSpec.scala
  arktwin/e2e/src/test/scala/arktwin/e2e/endpoints/EdgeConfigCoordinatePutScenario.scala
  arktwin/edge/src/main/resources/kamon.conf
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/configs/EdgeConfigSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSpec.scala
Labels: chore

#396 Fix Metals integration for Pekko gRPC generated code in common project
  arktwin/build.sbt
Labels: ci

#397 Update sbt, sbt-dependency-tree, ... to 1.11.5
  arktwin/project/build.properties
Labels: dependencies
