Repository arktwin/arktwin, pull requests merged in 2025-06, with the labels that each got.

#329 Update scalafmt-core to 3.9.7
  arktwin/.scalafmt.conf
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
Labels: dependencies

#332 Update sbt, sbt-dependency-tree, ... to 1.11.2
  arktwin/project/build.properties
  project/build.properties
Labels: dependencies

#330 Update jsoniter-scala-macros to 2.36.4
  arktwin/build.sbt
Labels: dependencies

#340 Make JSON serialization and deserialization stricter
  arktwin/e2e/src/test/scala/arktwin/e2e/endpoints/EdgeAgentsPostScenario.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeBulk.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/ErrorStatus.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/JsonDerivation.scala
Labels: enhancement

#341 Optimize case-insensitive enum parsing for config and JSON
  arktwin/edge/src/main/scala/arktwin/edge/util/EnumCaseInsensitiveJsonValueCodec.scala
Labels: chore

#343 Migrate test framework to FunSpec and improve code organization
  arktwin/.scalafix.conf
  arktwin/build.sbt
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSpec.scala
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/center/src/test/scala/arktwin/center/test/ActorTestBase.scala
  arktwin/common/src/main/protobuf/arktwin/center/services/chart.proto
  arktwin/common/src/main/protobuf/arktwin/common/data/duration.proto
  arktwin/common/src/main/protobuf/arktwin/common/data/timestamp.proto
  arktwin/common/src/main/protobuf/arktwin/package.proto
  arktwin/common/src/main/scala/arktwin/common/data/TaggedDuration.scala
  arktwin/common/src/main/scala/arktwin/common/data/TaggedTimestamp.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimeConstants.scala
  arktwin/common/src/main/scala/arktwin/common/util/EnumCaseInsensitiveConfigReader.scala
  arktwin/common/src/main/scala/arktwin/common/util/EnumCaseInsensitiveJsonValueCodec.scala
  arktwin/common/src/main/scala/arktwin/common/util/JsonDerivation.scala
  arktwin/common/src/main/scala/arktwin/common/util/SourceExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/util/TaggedDurationHistogram.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSpec.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/QuaternionEnuExtensionsSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedDurationSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedDurationSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedTimestampSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/TaggedTimestampSuite.scala
  arktwin/common/src/test/scala/arktwin/common/data/TransformEnuExtensionsSpec.scala
  arktwin/common/src/test/scala/arktwin/common/data/Vector3EnuExtensionsSpec.scala
  arktwin/common/src/test/scala/arktwin/common/util/EnumCaseInsensitiveConfigReaderSpec.scala
  arktwin/common/src/test/scala/arktwin/common/util/EnumCaseInsensitiveJsonValueCodecSpec.scala
  arktwin/common/src/test/scala/arktwin/common/util/JsonDerivationSpec.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/AxisConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeBulk.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/ErrorStatus.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/RequestValidator.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/EdgeConfiguratorSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ChartSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/ClockSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/RegisterSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/sinks/RegisterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSpec.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/test/ActorTestBase.scala
  arktwin/edge/src/test/scala/arktwin/edge/util/JsonDerivationSuite.scala
Labels: ci
