Repository arktwin/arktwin, pull requests merged in 2025-02, with the labels that each got.

#219 Refactor arktwin.common
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Chart.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterKamon.scala
  arktwin/center/src/test/scala/arktwin/center/actors/AtlasSuite.scala
  arktwin/common/src/main/scala/arktwin/center/services/ClockBaseExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/DurationExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/QuaternionEnuExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/TimestampExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/TransformEnuExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/data/Vector3EnuExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/util/EnumConfigIdentityReader.scala
  arktwin/common/src/main/scala/arktwin/common/util/GrpcHeaderKey.scala
  arktwin/common/src/main/scala/arktwin/common/util/LoggerConfigurator.scala
  arktwin/common/src/main/scala/arktwin/common/util/MailboxConfig.scala
  arktwin/common/src/main/scala/arktwin/common/util/TaggedDurationHistogram.scala
  arktwin/common/src/test/scala/arktwin/center/services/ClockBaseSuite.scala
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Register.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/AxisConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ClockConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Vector3.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeKamon.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
Labels: chore

#223 Update gatling-sbt to 4.11.2
  arktwin/project/plugins.sbt
Labels: dependencies

#227 Update scalafmt-core to 3.8.6
  arktwin/.scalafmt.conf
Labels: dependencies

#225 Update gatling-charts-highcharts to 3.13.3
  arktwin/build.sbt
Labels: dependencies

#222 Update openapi-circe-yaml to 0.11.7
  arktwin/build.sbt
Labels: dependencies

#228 Update cats-core to 2.13.0
  arktwin/build.sbt
Labels: dependencies

#221 Update jsoniter-scala-macros to 2.33.1
  arktwin/build.sbt
Labels: dependencies

#226 Update scala3-library to 3.6.3
  arktwin/build.sbt
  docker/center.dockerfile
  docker/edge.dockerfile
Labels: dependencies

#230 Update jsoniter-scala-macros to 2.33.2
  arktwin/build.sbt
Labels: dependencies

#232 Update gatling-sbt to 4.12.0
  arktwin/project/plugins.sbt
Labels: dependencies

#231 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.14
  arktwin/build.sbt
Labels: dependencies

#229 add test cases of coordinate transformation
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: ci

#233 Allow selecting rotation mode: extrinsic or intrinsic
  arktwin/e2e/src/test/scala/arktwin/e2e/endpoints/EdgeConfigCoordinatePutScenario.scala
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Rotation.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: enhancement

#220 Add Trace Logs
  arktwin/center/src/main/resources/pekko.conf
  arktwin/center/src/main/resources/reference.conf
  arktwin/center/src/main/scala/arktwin/center/Center.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Atlas.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Chart.scala
  arktwin/center/src/main/scala/arktwin/center/actors/ChartRecorder.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Clock.scala
  arktwin/center/src/main/scala/arktwin/center/actors/DeadLetterListener.scala
  arktwin/center/src/main/scala/arktwin/center/actors/Register.scala
  arktwin/center/src/main/scala/arktwin/center/configs/CenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/configs/StaticCenterConfig.scala
  arktwin/center/src/main/scala/arktwin/center/services/ChartService.scala
  arktwin/center/src/main/scala/arktwin/center/services/ClockService.scala
  arktwin/center/src/main/scala/arktwin/center/services/RegisterService.scala
  arktwin/center/src/main/scala/arktwin/center/util/CenterReporter.scala
  arktwin/common/src/main/scala/arktwin/common/util/ActorLogger.scala
  arktwin/common/src/main/scala/arktwin/common/util/BehaviorsExtensions.scala
  arktwin/common/src/main/scala/arktwin/common/util/LoggerConfigurator.scala
  arktwin/common/src/main/scala/arktwin/common/util/PureConfigHints.scala
  arktwin/common/src/main/scala/arktwin/common/util/SourceExtensions.scala
  arktwin/edge/src/main/resources/pekko.conf
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/Edge.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/DeadLetterListener.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/EdgeConfigurator.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapter.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Chart.scala
  arktwin/edge/src/main/scala/arktwin/edge/actors/sinks/Clock.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/EdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/StaticEdgeConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ChartConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/ClockConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/connectors/RegisterConnector.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterAgentsDelete.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/CenterClockSpeedPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPost.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeAgentsPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCullingPut.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigGet.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeNeighborsQuery.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EdgeReporter.scala
  arktwin/edge/src/main/scala/arktwin/edge/util/EndpointExtensions.scala
Labels: enhancement

#237 Update gatling-charts-highcharts to 3.13.4
  arktwin/build.sbt
Labels: dependencies

#235 Update gatling-sbt to 4.13.0
  arktwin/project/plugins.sbt
Labels: dependencies

#234 Update tapir-core, tapir-jsoniter-scala, ... to 1.11.15
  arktwin/build.sbt
Labels: dependencies

#238 Update scalafmt-core to 3.9.0
  arktwin/.scalafmt.conf
Labels: dependencies

#240 Fix the filter pattern for release tags in GitHub Actions
  .github/workflows/github-pages.yaml
Labels: ci

#239 Add descriptions about the coordinate properties to the README
  README.md
  arktwin/e2e/src/test/scala/arktwin/e2e/endpoints/EdgeConfigCoordinatePutScenario.scala
  arktwin/edge/src/main/resources/reference.conf
  arktwin/edge/src/main/scala/arktwin/edge/configs/CoordinateConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/configs/RotationConfig.scala
  arktwin/edge/src/main/scala/arktwin/edge/data/Transform.scala
  arktwin/edge/src/main/scala/arktwin/edge/endpoints/EdgeConfigCoordinatePut.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeAgentsPutAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/actors/adapters/EdgeNeighborsQueryAdapterSuite.scala
  arktwin/edge/src/test/scala/arktwin/edge/data/TransformSuite.scala
Labels: documentation

#242 Update scalafmt-core to 3.9.1
  arktwin/.scalafmt.conf
Labels: dependencies

#241 Update sbt-scalafix to 0.14.2
  arktwin/project/plugins.sbt
Labels: dependencies
